bot_token: '7768998421:AAG2bzf82CG-LV1mojxJ945K2-Mclbnv54w'
db_url: 'postgres://postgres:0904@localhost:5432/Horeca'

price_options:
  ONE_DAY: 100
  ONE_WEEK: 300
  VIP: 2000
  RESUME_SUB: 1000
  VIEW_COMMENTS: 1000

redis:
  host: 'caboose.proxy.rlwy.net'
  port: 40339
  username: 'default'
  password: 'KMLpXfMwOjwOJqOCrUOQkxekcCgJLdhw'
